### PR TITLE
Add Plugins

### LINKED ISSUE #92: Plugin Support

### PR DESCRIPTION
**Pull request by minitriga**
Fixes #92 

Add the ability to hook into the lifecycle of the backup and git processes so that custom python plugins can be executed. The requirement for this is to be able to notify 3rd party systems if backups have succeeded, failed etc.. 

Functionality:

- [x] Backup Successful
- [x] Backup Failed
- [x] Backup Report
- [x] Git Save Success
- [x] Git Save Failed

Todo:
- [x] Test Cases
- [x] Documentation

Current functionality looks like the following:

1. Create a folder called plugins
2. Add the plugins path to `netcfgbu.toml` within default with the key `plugins_dir`
3. Add a python file within the plugins folder that looks like the following:

```python
from netcfgbu import Plugin

class ScienceLogic(Plugin):
    name = "ScienceLogic"

    def backup_success(rec: dict, res: bool):
        print("Backup Successful")

    def backup_failed(rec: dict, exc: str):
        print("Backup Failed")

    def report(report):
        print("Backup Report")

class test(Plugin):
    name = "test"

    def git_report(success, tag_name):
        print("git output")
        print(success, tag_name)
```

### CODE REVIEW

**Comment by jeremyschulman** [comment]
Thank you, very nice!

**Comment by jeremyschulman** [comment]
Please bump the VERSION to 0.8.0

**Comment by minitriga** [comment]
@jeremyschulman  All done

**Comment by minitriga** [comment]
Project currently using the plugin functionality. 

- [Microsoft Teams with Gitlab Integration](https://github.com/JMast3rs/netcfgbu-plugin-teams)

**Pull request merged**
